# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bash_profile ]; then
	. ~/.bash_aliases
fi

source /opt/ros/kinetic/setup.bash
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@: \[\e[33m\]\w\[\e[0m\]\n\!\$ '

setxkbmap -option caps:ctrl_modifier
