
source /opt/ros/kinetic/setup.bash
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@: \[\e[33m\]\w\[\e[0m\]\n\!\$ '

LS_COLORS=$LS_COLORS:'di=1;37'
export LS_COLORS


setxkbmap -option caps:ctrl_modifier
xinput --set-prop "pointer:MOSART Semi. 2.4G RF Keyboard & Mouse" "Device Accel Constant Deceleration" 2.0
gsettings set org.gnome.settings-daemon.plugins.background active true
