set nocompatible
filetype off

" If vundle isn't installed, we better install it.
if !isdirectory(expand("~/.vim/bundle/Vundle.vim/.git"))
    !git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
endif

" Include Vundle on the runtime path and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle should manage Vundle.
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'mbbill/undotree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'kshenoy/vim-signature'
Plugin 'SearchAlternatives'
Plugin 'ingo-library'
Plugin 'Raimondi/delimitMate'
Plugin 'morhetz/gruvbox'
" End Plugins

call vundle#end()
filetype plugin indent on

" Persistent undo
set undofile
set undodir=~/.vim/undo

set undolevels=1000
set undoreload=10000

" Line Wrapping
set nowrap
set colorcolumn=81

" Line Numbering
set number

" Whitespace Management
set tabstop=4
set softtabstop=4
set expandtab
set backspace=indent,eol,start

" Java indents
set autoindent
set smartindent

" Syntax Highlighting
filetype on
filetype plugin on
syntax enable

" Searching
set incsearch
set hlsearch

" Disable auto-indentation.
set paste

" Coloring.
colorscheme desert
highlight ColorColumn ctermbg=gray

" Cleanup
set nohidden

" Setting smart case sensitivity for searching.
set ignorecase
set smartcase

" DelimiteMate
let delimitMateAutoClose = 1
let delimitMate_expand_cr = 1

" Coloring
set background=dark
hi CursorLine cterm=bold ctermbg=234
colorscheme gruvbox
let g:gruxbox_contrast_dark= 'hard'
let g:gruvbox_number_columnt = 'bg4'
let g:gruvbox_improved_warnings = 1
