#!/bin/sh

# We should fail if we encounter errors.
set -e

# We should run this from the working directory of this script.
cd $(readlink -f $(dirname "$0"))

# Create links of all our dot files.
for dotfile in $(find "dotfiles/" -type f); do
    # Derive the name of the file.
    name=.$(basename "$dotfile")

    # If the file and is a real file, back it up.
    if [ -f ~/$name ]; then
        mv ~/$name ~/$name.old
    fi

    # If the file is still there, it's a symlink. Remove it.
    rm -f ~/$name

    # Create a symlink.
    ln -s $(readlink -f "$dotfile") ~/$name
done

#nvim
mkdir -p ~/.config/nvim
if [ -f ~/.config/nvim/init.vim ]; then
	mv ~/.config/nvim/init.vim ~/.config/nvim/init.vim.old
fi
rm ~/.config/nvim/init.vim
ln -s $(readlink -f "init.vim") ~/.config/nvim

mkdir -p ~/.config/i3
for dotfile in $(find "i3/" -type f); do
	name=.$(basename "$dotfile")

	if [ -f ~/.config/i3/$name ]; then
		mv ~/.config/i3/$name ~/.config/i3/$name.old
	fi

	rm -f ~/.config/i3/$name

	ln -s $(readlink -f "$dotfile") ~/.config/i3/$name
done
#########################
# Software Installation #
#########################

if [ -n "$(command -v yum)" ]; then
    # General utilities.
    sudo yum install -y vim
    sudo yum install -y htop
    sudo yum install -y jq
    sudo yum install -y tmux
fi

if [ -n "$(command -v apt-get)" ]; then
    # General utilities.
    sudo apt-get install -y vim
    sudo apt-get install -y htop
    sudo apt-get install -y jq
    sudo apt-get install -y tmux
fi

if [[-n "$(command -v pacman)" ]]; then
	# General utilities
	sudo pacman -S --no-confirm vim
	sudo pacman -S --no-confirm tmux
    sudo pacman -S --no-confirm htop
    sudo pacman -S --no-confirm jq
fi
###########################
# Vim Plugin Installation #
###########################
if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall

#####################
# Git Configuration #
#####################

# Apparently git defaults to using 'vi' instead of 'vim', causing some
# unpleasant warnings when writing commit messages. Let's use 'vim'
# instead.
git config --global core.editor nvim
git config --global user.email "nickkryan77@gmail.com"
git config --global user.name "nickkryan"

#Oh-My-Zsh
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

#Powerline Fonts
cd ~ && mkdir Themes && cd Themes
git clone https://github.com/powerline/fonts.git
./install.sh
